site_name: 开源操作系统训练营课程
repo_url: https://github.com/os2edu/trainingcamp.git
# repo_name: Dongjianhao123/mkdocs-test

theme:
  name: material
  logo: https://os2edu.cn/assets/images/logo.png
  favicon: https://os2edu.cn/assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    # - navigation.
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  homepage: https://os2edu.cn

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

nav:
  - 主页: index.md
  - 第一阶段(Rust编程):
      - Rustling练习入门，基本数据类型，slice类型，所有权: Rust/page1.md
      - crate，option，trait和泛型及生命周期: Rust/page2.md
      - 智能指针，迭代器和闭包，并发编程: Rust/page3.md
      - Rustlings答疑讲解: Rust/page4.md
  - 第二阶段(RISC-V & OS Kernel):
      - 从一个bare metal app开始: rCore/page1.md
      - rCore Tutorial内存管理和页表: rCore/page2.md
      - rCore Tutorial进程管理: rCore/page3.md
      - rCore Tutorial文件系统easy-fs: rCore/page4.md
      - rCore Tutorial作业讲解和答疑: rCore/page5.md
      - ArceOS基础: rCore/page6.md
  - 第三阶段(ArceOS & Hypervisor):
      - ArceOS单内核Unikernel: ArceOS/page1.md
      - ArceOS宏内核: ArceOS/page2.md
      - Rust for Linux驱动: ArceOS/page3.md
      - Hypervisor虚拟化: ArceOS/page4.md
      - ChenLongOS辰龙操作系统发行版: ArceOS/page5.md
      - 基于协程异步机制的操作系统/驱动: ArceOS/page6.md
